# agents/coder_agent.py
import asyncio
import json
from mcp import Client, aiohttp

# This should point to your locally running Filesystem MCP server.
# See: https://github.com/modelcontextprotocol/servers/tree/main/filesystem
MCP_FILESYSTEM_URL = "http://localhost:8080" # Example URL

async def handle_code(plan_details: str) -> str:
    """
    Generates code based on a plan and saves it using a Filesystem MCP server.

    NOTE: This agent requires a Filesystem MCP server to be running locally.
    """
    print("🤖 Coder Agent: Generating code and contacting Filesystem MCP server...")
    
    # In a real implementation, this prompt would be sent to an LLM
    # to generate the actual code based on the plan.
    # For this template, we will simulate the LLM's output.
    simulated_llm_code_output = """
# This code was generated by the Coder Agent
def hello_world():
    print("Hello from generated code!")

hello_world()
"""
    file_to_write = "generated_code.py"
    print(f"Simulated LLM generating code to be saved in '{file_to_write}'...")

    try:
        async with aiohttp.ClientSession() as session:
            client = Client(session)
            
            # Call the 'writeFile' tool on the local Filesystem server
            response = await client.request(
                MCP_FILESYSTEM_URL,
                "writeFile",
                {
                    "path": file_to_write,
                    "content": simulated_llm_code_output,
                }
            )
            
            result = json.loads(response)
            if result.get("success"):
                return f"✅ CODE CREATED: Successfully wrote code to '{file_to_write}' via Filesystem MCP."
            else:
                return f"❌ CODER FAILED: MCP server returned an error: {result.get('error')}"

    except Exception as e:
        return f"❌ CODER FAILED: Could not connect to the local Filesystem MCP server on {MCP_FILESYSTEM_URL}. Is it running? Error: {e}"
