# agents/data_fetcher_agent.py
import asyncio
import json
from mcp import Client, aiohttp

# This should point to a running generic HTTP Client MCP server.
MCP_HTTP_URL = "http://localhost:8082" # Example URL

async def handle_data_fetch(task_details: str) -> str:
    """
    Writes a script for fetching data based on a task.
    
    This agent uses a generic HTTP MCP server to generate a data fetching script.
    In a real scenario, the LLM would generate a Python script using 'requests'
    or a similar library.
    """
    print("🤖 Data Fetcher Agent: Generating a data fetching script...")

    # For the template, we'll simulate the LLM's output
    simulated_fetch_script = f"""
import requests
import json

# This script was generated by the Data Fetcher Agent
# based on the task: '{task_details}'

def fetch_data():
    try:
        # Example: Fetching data from a placeholder API
        api_url = "https://api.placeholder.com/data"
        response = requests.get(api_url, timeout=10)
        response.raise_for_status() # Raise an exception for bad status codes
        print("Successfully fetched data:")
        print(response.json())
    except requests.exceptions.RequestException as e:
        print(f"Error fetching data: {e}")

if __name__ == "__main__":
    fetch_data()
"""
    
    # This agent's output is the script itself, ready to be saved by the Coder Agent.
    # A more advanced version could use the Filesystem MCP directly.
    # For a clean template, we'll have it return the code for another agent to handle.
    return f"✅ DATA FETCHER SCRIPT CREATED:\n\n```python\n{simulated_fetch_script}\n```"